version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest"
  
  jobs:
    pre_build:
      - export WARN_ON_DATA_CONFIGURATION_FAILURE="False"
      - export RAISE_ON_DATA_CONFIGURATION_FAILURE="False"

conda:
  environment: docs/environment-cpu.yaml

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf