[pytest]
markers =
    slowish: marks test as slowish, i.e. not fast and not really slow :)
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: mark an integration test
    usescuda: mark a test that uses cuda

testpaths = tests/