# This environment file is intended for the build process at readthedocs.io.
# It hsould be kept in close sync with the environment file in the parent
# directory, environment.yaml, which is intended for local development.
# Here, we also specify the sphinx-specific packages that are mostly pip-only
name: woodanalysis

channels:
  - pytorch
  - conda-forge

dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - numpy
  - tqdm
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - zarr
  - h5py
  - tensorboard
  - seaborn
  - rich
  - monai
  - pydantic
  - pillow
  - pytest
  - ruamel.yaml
  - pip>=20
  - pip:
      - sphinx-argparse-cli
      - sphinx-rtd-theme
      - sphinxcontrib-jquery