name: woodnet package CI

on: [push]

env:
  FORCE_COLOR: "1"

jobs:
  test-linux-conda:
    name: job-conda-(${{ matrix.python-version }}::${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: woodanalysis
          environment-file: environment-cpu.yaml

      - name: Conda info
        shell: bash -el {0}
        run: |
          conda info
          conda list

      - name: Test
        shell: bash -el {0}
        run: |
          pip install --editable . --no-deps
          pytest -m 'not usescuda'


  test-linux-uv:
    name: job-uv-(${{ matrix.python-version }}::${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest -m 'not usescuda'


  lint:
    name: job-lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pyversion: ["py310", "py311", "py312", "py313"]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v2
        with:
          args: "check . --target-version ${{ matrix.pyversion }}"
